---
version: '3'

services:
  drupal:
    image: wdseelig:latest
    container_name: WCGOP
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      # TODO: Create a new hash salt for this.
      DRUPAL_HASH_SALT: 'fe918c992fb1bcfa01f32303c8b21f3d0a0'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
      - "2222:22"
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    volumes: ['./:/var/www/html:rw,delegated']

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal 
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      
  mysql2:
    image: mysql:5.7
    container_name: olddrupal
    environment:
      MYSQL_ROOT_PASSWORD: 'wd17hh21'
      MYSQL_DATABASE: washgopc_GOPV7V2
      MYSQL_USER: gopdbadmin
      MYSQL_PASSWORD: 18WMTNwcta65
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - ./May2020Dump.sql:/docker-entrypoint-initdb.d/May2020Dump.sql

  
      
      
