<?php

/**
 * @file
 * Provides a displayqvf entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function displayqvf_theme() {
  return [
    'displayqvf' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for displayqvf templates.
 *
 * Default template: displayqvf.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the displayqvf information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_displayqvf(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
