features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 0
  logo: true
  name: true
  node_user_picture: true
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: rss.xml
copyright_text: 'Copyright 2016· All rights reserved'
show_social_icon: 1
show_credit_link: 1
_core:
  default_config_hash: OJYcjUflz8lXqjnwYANgc7jzKuPZ4Ard4CsG9F4P-QA
logo:
  use_default: 0
  path: 'public://NewWCGOPLogoTR.png'
favicon:
  use_default: 0
  path: ''
